# Generated by Django 6.0.3 on 2026-03-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0003_alter_products_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.TextField()),
                ('image', models.ImageField(upload_to='hero/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.category')),
            ],
            options={
                'db_table': 'HeroCategory',
            },
        ),
    ]
