# Generated by Django 6.0.3 on 2026-03-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
