# Generated by Django 6.0.3 on 2026-03-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_order',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Order Placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Placed', max_length=50),
        ),
    ]
